title: "Cybergod: Reborn RPG"
description: "Site for Cybergod: Reborn tabletop Roleplaying Game"
theme: just-the-docs

url: https://catmorbid.github.io/cybergod-public

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
